### ISSUE TITLE
release 1.5.2 failed

### ISSUE THREAD

**Issue by jangalinski** [camunda-community-hub/camunda-bpm-custom-batch#38]
a github release was created, but no maven central artifacts are visible

https://search.maven.org/search?q=g:org.camunda.bpm.extension.batch%20AND%20a:camunda-bpm-custom-batch-core%20AND%20v:1.5.2

**Comment by jangalinski** [comment]
Rin, can you check, please?

**Comment by celanthe** [comment]
Hi @jangalinski -- Thanks for opening this issue! I tried to re-run the Action on the hope that it would complete/fill in the missing information, but it's currently failing for me. @Langleu, is there a way I can resolve this in order to help Jan get this release staged so I can publish on Maven Central? TYSM!

**Comment by celanthe** [comment]
Hi again @jangalinski -- I went ahead and released this on Sonatype and if you could let me know if the artifact is available, that would be great! It can take a few hours and up to a few days for artifacts to be visible, but I hope it won't take too long! :) If that doesn't work, please do let me know and we can troubleshoot further for sure!

**Comment by zambrovski** [comment]
Just a question, Rin. Is there a reason, why the Sonatype isn't automated?

**Comment by celanthe** [comment]
Hi @zambrovski! Sonatype isn't automated for a few reasons, firstly for security. Second, if there were ever faulty releases, they would permanently be on Maven central since every object is immutable. That being said, I am happy to propose looking into this further to the team, and will take this feedback into consideration as we continue to shape the future of the Community Hub! :)

**Comment by zambrovski** [comment]
Hm. Don't get it. If you provide access to the repo maintainer, who can click on release button and this crates a release and then you ask the same person for ok? So there is no real check neither for security nor for the content, since no one would check the intermediate release on sonatype (due to lack of permissions). 

So why not simplifying this step and binding the release publishing to release production? In the Open source world - a wrong release is not a problem if that is replaced fast... having manual steps - you slow down the release process... just my 5 cents for this... 

If versioning scheme is maintained, everyone would go for the latest patch release ...

**Comment by celanthe** [comment]
Hi @jangalinski -- I just checked [https://search.maven.org/search?q=g:org.camunda.bpm.extension.batch%20AND%20a:camunda-bpm-custom-batch-core%20AND%20v:1.5.2](https://search.maven.org/search?q=g:org.camunda.bpm.extension.batch%20AND%20a:camunda-bpm-custom-batch-core%20AND%20v:1.5.2) and the artifact appears to be available now! Can you confirm that's working as intended? Thank you kindly!

**Comment by jangalinski** [comment]
Thanks celanthe, can confirm it is available on central. And btw: this is not my release, @pschalk triggered it ... I just found out that it is not available on central.

I do not really care how we solve this problem, but we have a "two phase commit" kinda problem here.   Github release is done, the right column features a prominent label "latest release: 1.5.2". The "release issue" is closed ... the code is tagged ... but I cannot use the lib from central (unless I have very keen eyes and check the maven central badge on the readme to see that 1.5.2 is in fact _not_ on central). And then I as the author (or just someone interested in using the lib) have to ask. And wait. 

So we need a "happy path" where when nothing special happens, I can just assume that gh-release and sonatype release happen at the same time, and that due to cache/index updates it just may take a few hours until I see the lib on central.
If this is automated or using some "high prio" user task on your side ... open for discussion.
